# Author: Hitesh Paul <github at hiteshpaul.com>
# Example configuration file for Marcos file manager(https://github.com/TerminalWitchcraft/marcos)
# All options are optional. If any option is missing, the default value is loaded at runtime.


[options]

	# Metric to display size of various items. Possible values "bits", "bytes".
	size = "bits"

	# Show hidden files? Possible values: true, false
	show_hidden = false

	# Ask for confirmation when deleting modifying on disk? Possible values true, false
	confirm = true

	# Preview images? Possible values true, false
	show_images = false

	# Status bar position. Possible values: "top", "bottom"
	status_position = "bottom"

	# Shorten title. Possible value: any positive number which defines the number
	# of directories to show. If set to 0, full path will be shown
	shorten_title = 0

	# [TODO] Sort. Possible values: "default", "size", "type", "atime"
	# sort = "default"

	# Preview max file size. Files larger than this size will not be previewed.
	# Value in bytes.
	preview_max_size = 102400

	# Delay in ms. Marcos updates directories after the specified value.
	delay_idle = 2000

	# Show line number? Possible value: true, false
	line_numbers = false

	# Show popup windows on confirmation?[Defaults to status_bar] Possible values: true, false
	show_popup = true

# Display disk usage at specified mount point with display name.
[mount.rootfs]
	point = "/"



[key_maps]
	# TODO
	quit			= "q"
	select_up		= "k"
	select_down 		= "j"
	# select_first		= "gg"
	# select_last 		= "G"
	# select_n		= "*g"
	back 			= "h"
	forward 		= "l"
	prompt			= ":"
	show_hidden 		= "za"
	yank 			= "y"
	cut			= "x"
	paste			= "p"
	paste_replace 		= "P"
	rename 			= "r"
	delete_with_cfm 	= "dd"
	new_file		= "o"
	new_folder 		= "O"
	# create bookmark
	# jumpto bookmark
	search 			= "/"
	next_match 		= "n"
	previous_match 		= "N"
	visual 			= "v"
	visual_all 		= "V"
	refresh			= "C-r"
